#!/bin/bash

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth

#mkdir -p /tmp/$USER/

if [ ! -f "$XAUTH" ]; then 
	touch $XAUTH
	xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
fi

xhost +local:root
docker run -it --rm \
	--network host \
	--privileged \
	--env XAUTHORITH=${XAUTH} \
	--env DISPLAY=$DISPLAY \
	--env QT_GRAPHICSYSTEM=native \
	--env QT_X11_NO_MITSHM=1 \
	--volume $XSOCK:$XSOCK:rw \
	--volume $XAUTH:$XAUTH:rw \
	--volume /root/ros2_foxy:/root/ros_ws \
	kovan:test /bin/bash
xhost -local:root
