#!/bin/bash

srcpath="$(dirname $(pwd))/share"
binfile='testbin'
#imgname=ros:foxy-ros-base
imgname=kovan:devel

docker build -f Dockerfile -t $imgname ../share

sed "s|_ROS2_SHARE_|$srcpath|g" base > /home/car-rl/.local/bin/ros2
sed -i "s|_ROS2_IMAGE_|$imgname|g" /home/car-rl/.local/bin/ros2
chmod +x /home/car-rl/.local/bin/ros2

