#!/bin/bash

xhost +local:root
docker run -it --rm \
	--network host \
	--env DISPLAY \
	--env QT_X11_NO_MITSHM=1 \
	--volume ~/ros2_foxy:/root/ros_ws \
	--volume /tmp/.X11-unix:/tmp/.X11-unix:rw \
	kovan:latest bash
xhost -local:root
