#!/bin/bash

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth

mkdir -p /tmp/dockerd

if [ ! -f "$XAUTH" ]; then 
	touch $XAUTH
	xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
fi

./paste_dockerd &
xhost +local:root
docker run -it --rm \
	--network host \
	--privileged \
	--env XAUTHORITHY=${XAUTH} \
	--env DISPLAY=$DISPLAY \
	--env QT_GRAPHICSYSTEM=native \
	--env QT_X11_NO_MITSHM=1 \
	-v /dev:/dev \
	--volume $XSOCK:$XSOCK:rw \
	--volume $XAUTH:$XAUTH:rw \
	--volume /home/car-rl/Desktop/car_rl/share:/root/host_ws/src \
	kovan:develwip "$@" 
xhost -local:root
